version: "3"
services:
  api:
    image: lacham378/fastapi
    depends_on:
      - postgres
    # env_file:
    #   - ./.env
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:    
      - "80:8000"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: