version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    # env_file:
    #   - ./.env
    environment:
      - DB_HOSTNAME=postgres
      - DB_PORT=5432 
      - DB_PASSWORD=xxxxx
      - DB_NAME=fastapi
      - DB_USERNAME=postgres
      - SECRET_KEY=7fa2bb2bba376c2eec64j75c61300d8d3ac27594a45908fb2a719eb42c78be00 
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:    
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=xxxxx
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: