"""add phone_number col

Revision ID: 447e7dbd3082
Revises: d737b028b3c1
Create Date: 2022-12-20 17:16:24.498120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447e7dbd3082'
down_revision = 'd737b028b3c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
