name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: setup Python  3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update pip to latest version
        run: python -m pip install --upgrade pip
      - name: Installing all dependencies
        run: pip install -r requirements.txt
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"




      # - name: fast API Github repo 
      #   run: echo "hello git pull"


  # push:
  #   branches: 
  #     - "main"
  #     - "a_branch"
  #     - "b_branch"
  #     - "c_branch"
  # pull_request:
  #   branches:
  #     - "test_branch"

# Sequence of patterns matched against refs/tags
#     tags:        
#       - v2
#       - v1.*
      

      
      
